export const ROLE_CODES = [
  "administrator",
  "purchaser",
  "warehouse_staff",
  "sales_staff",
  "company_principal",
] as const;

export type RoleCode = (typeof ROLE_CODES)[number];

export const DATA_SCOPE_TYPES = [
  "all",
  "self_created",
  "business_related",
  "warehouse",
  "store",
  "manufacturer_derived",
] as const;

export type DataScopeType = (typeof DATA_SCOPE_TYPES)[number];

export const PERMISSION_CATALOG = {
  "master.product": ["read", "create", "update", "enable", "disable"],
  "master.sku": ["read", "create", "update", "enable", "disable"],
  "master.category": ["read", "create", "update", "enable", "disable"],
  "master.brand": ["read", "create", "update", "enable", "disable"],
  "master.supplier": ["read", "create", "update", "enable", "disable"],
  "master.manufacturer": ["read", "create", "update", "enable", "disable"],
  "master.warehouse": ["read", "create", "update", "enable", "disable"],
  "master.platform": ["read", "create", "update", "enable", "disable"],
  "master.store": ["read", "create", "update", "enable", "disable"],
  "master.customer-snapshot": ["read"],
  "purchase.order": [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "approve",
    "reject",
    "unapprove",
    "cancel",
    "void",
    "export",
  ],
  "purchase.payment": ["read", "create"],
  "purchase.return": [
    "read",
    "create",
    "update",
    "submit",
    "approve",
    "reject",
    "unapprove",
    "cancel",
    "void",
    "confirm-outbound",
  ],
  "production.order": [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "approve",
    "reject",
    "unapprove",
    "start",
    "cancel",
    "void",
    "export",
  ],
  "production.progress": ["read", "create"],
  "production.completion": ["read", "create", "confirm", "revoke", "void"],
  "production.payment": ["read", "create"],
  "inspection.order": ["read", "create", "update", "submit", "confirm", "revoke", "void", "export"],
  "inventory.stock": ["read"],
  "inventory.transaction": ["read"],
  "inventory.alert": ["read", "view", "handle", "close"],
  "inventory.adjustment": [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "approve",
    "reject",
    "unapprove",
    "cancel",
    "void",
    "execute",
    "export",
  ],
  "inventory.stock-count": [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "approve",
    "reject",
    "start",
    "initial-count",
    "recount",
    "complete",
    "cancel",
    "void",
    "export",
  ],
  "inventory.damage": [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "approve",
    "reject",
    "cancel",
    "confirm-outbound",
    "validate",
    "export",
  ],
  "inbound.order": [
    "read",
    "create-purchase",
    "create-production",
    "create-other",
    "update",
    "submit",
    "withdraw",
    "approve",
    "reject",
    "unapprove",
    "cancel",
    "confirm",
    "reverse",
    "export",
  ],
  "outbound.order": [
    "read",
    "create-domestic-sales",
    "create-other",
    "update",
    "submit",
    "withdraw",
    "approve",
    "reject",
    "unapprove",
    "cancel",
    "confirm",
    "reverse",
    "export",
  ],
  "outbound.sales-return": [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "approve",
    "reject",
    "cancel",
    "confirm-inbound",
    "export",
  ],
  "transfer.order": [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "approve",
    "reject",
    "unapprove",
    "cancel",
    "ship",
    "receive",
    "export",
  ],
  "cross-border.shipment": [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "approve",
    "reject",
    "unapprove",
    "cancel",
    "void",
    "dispatch",
    "export",
  ],
  "cross-border.overseas-inventory": ["read"],
  "cross-border.import-result": ["read"],
  "cross-border.source-trace": ["read"],
  "import.task": ["read", "create", "cancel", "validate", "execute"],
  "import.template": ["read", "validate"],
  "import.history": ["export"],
  "attachment.file": ["upload", "read", "download", "link", "unlink", "delete"],
  "audit.log": ["read", "export"],
  "security.user": ["read", "create", "update", "enable", "disable"],
  "security.role": ["read", "create", "update", "enable", "disable", "assign"],
  "security.permission": ["read", "assign"],
  "security.setting": ["read", "update"],
  "field.amount": ["read"],
  "field.cost": ["read"],
  "field.personal-data": ["read"],
  "field.supplier-sensitive": ["read"],
  "field.manufacturer-sensitive": ["read"],
  "field.attachment-sensitive": ["read"],
  "field.import-raw-data": ["read"],
  "field.audit-sensitive": ["read"],
} as const;

type PermissionResource = keyof typeof PERMISSION_CATALOG;
type PermissionAction<R extends PermissionResource> = (typeof PERMISSION_CATALOG)[R][number];

export type PermissionCode = {
  [R in PermissionResource]: `${R}.${PermissionAction<R>}`;
}[PermissionResource];

function permissionsFor<R extends PermissionResource>(
  resource: R,
  actions: readonly PermissionAction<R>[],
): PermissionCode[] {
  return actions.map((action) => `${resource}.${action}` as PermissionCode);
}

function allFor<R extends PermissionResource>(resource: R): PermissionCode[] {
  return permissionsFor(resource, PERMISSION_CATALOG[resource]);
}

function combine(...groups: readonly PermissionCode[][]): readonly PermissionCode[] {
  return Object.freeze([...new Set(groups.flat())]);
}

export const PERMISSION_CODES = Object.freeze(
  (Object.keys(PERMISSION_CATALOG) as PermissionResource[]).flatMap((resource) => allFor(resource)),
);

const PURCHASER_PERMISSIONS = combine(
  allFor("master.product"),
  allFor("master.sku"),
  allFor("master.category"),
  allFor("master.brand"),
  allFor("master.supplier"),
  allFor("master.manufacturer"),
  permissionsFor("master.warehouse", ["read"]),
  permissionsFor("master.platform", ["read"]),
  permissionsFor("master.store", ["read"]),
  allFor("purchase.order"),
  allFor("purchase.payment"),
  permissionsFor("purchase.return", [
    "read",
    "create",
    "update",
    "submit",
    "approve",
    "reject",
    "unapprove",
    "cancel",
    "void",
  ]),
  allFor("inspection.order"),
  allFor("inventory.stock"),
  allFor("inventory.transaction"),
  permissionsFor("inventory.alert", ["read"]),
  permissionsFor("inbound.order", ["read", "create-purchase"]),
  permissionsFor("import.task", ["read", "create", "cancel", "validate"]),
  allFor("import.template"),
  allFor("import.history"),
  permissionsFor("attachment.file", ["upload", "read", "download", "link", "unlink"]),
  allFor("field.amount"),
  allFor("field.supplier-sensitive"),
  allFor("field.manufacturer-sensitive"),
);

const WAREHOUSE_PERMISSIONS = combine(
  permissionsFor("master.product", ["read"]),
  permissionsFor("master.sku", ["read"]),
  permissionsFor("master.category", ["read"]),
  permissionsFor("master.brand", ["read"]),
  permissionsFor("master.supplier", ["read"]),
  permissionsFor("master.manufacturer", ["read"]),
  allFor("master.warehouse"),
  permissionsFor("master.platform", ["read"]),
  permissionsFor("master.store", ["read"]),
  permissionsFor("purchase.order", ["read"]),
  permissionsFor("purchase.return", ["read", "confirm-outbound"]),
  permissionsFor("production.order", ["read"]),
  allFor("production.progress"),
  allFor("production.completion"),
  allFor("inspection.order"),
  allFor("inventory.stock"),
  allFor("inventory.transaction"),
  allFor("inventory.alert"),
  permissionsFor("inventory.adjustment", [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "cancel",
    "execute",
  ]),
  permissionsFor("inventory.stock-count", [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "start",
    "initial-count",
    "recount",
    "complete",
    "cancel",
    "export",
  ]),
  permissionsFor("inventory.damage", [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "cancel",
    "confirm-outbound",
    "validate",
  ]),
  permissionsFor("inbound.order", [
    "read",
    "create-purchase",
    "create-production",
    "create-other",
    "update",
    "submit",
    "withdraw",
    "cancel",
    "confirm",
  ]),
  permissionsFor("outbound.order", [
    "read",
    "create-other",
    "update",
    "submit",
    "withdraw",
    "cancel",
    "confirm",
  ]),
  permissionsFor("outbound.sales-return", ["read", "confirm-inbound"]),
  permissionsFor("transfer.order", [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "cancel",
    "ship",
    "receive",
  ]),
  permissionsFor("cross-border.shipment", ["read", "dispatch"]),
  allFor("cross-border.overseas-inventory"),
  allFor("cross-border.import-result"),
  allFor("cross-border.source-trace"),
  allFor("import.task"),
  allFor("import.template"),
  allFor("import.history"),
  permissionsFor("attachment.file", ["upload", "read", "download", "link", "unlink"]),
  allFor("field.cost"),
  allFor("field.import-raw-data"),
);

const SALES_PERMISSIONS = combine(
  permissionsFor("master.product", ["read"]),
  permissionsFor("master.sku", ["read"]),
  permissionsFor("master.category", ["read"]),
  permissionsFor("master.brand", ["read"]),
  permissionsFor("master.warehouse", ["read"]),
  permissionsFor("master.platform", ["read"]),
  permissionsFor("master.store", ["read", "update"]),
  allFor("master.customer-snapshot"),
  allFor("inventory.stock"),
  allFor("inventory.transaction"),
  permissionsFor("inventory.alert", ["read"]),
  permissionsFor("outbound.order", [
    "read",
    "create-domestic-sales",
    "update",
    "submit",
    "withdraw",
    "cancel",
  ]),
  permissionsFor("outbound.sales-return", [
    "read",
    "create",
    "update",
    "submit",
    "withdraw",
    "cancel",
    "export",
  ]),
  permissionsFor("import.task", ["read", "create", "cancel", "validate"]),
  allFor("import.template"),
  allFor("import.history"),
  permissionsFor("attachment.file", ["upload", "read", "download", "link", "unlink"]),
  allFor("field.personal-data"),
);

const PRINCIPAL_PERMISSIONS = combine(
  permissionsFor("master.product", ["read"]),
  permissionsFor("master.sku", ["read"]),
  permissionsFor("master.category", ["read"]),
  permissionsFor("master.brand", ["read"]),
  permissionsFor("master.supplier", ["read"]),
  permissionsFor("master.manufacturer", ["read"]),
  permissionsFor("master.warehouse", ["read"]),
  permissionsFor("master.platform", ["read"]),
  permissionsFor("master.store", ["read"]),
  allFor("master.customer-snapshot"),
  permissionsFor("purchase.order", [
    "read",
    "approve",
    "reject",
    "unapprove",
    "cancel",
    "void",
    "export",
  ]),
  permissionsFor("purchase.payment", ["read"]),
  permissionsFor("purchase.return", ["read", "approve", "reject", "unapprove", "void"]),
  permissionsFor("production.order", ["read", "approve", "reject", "unapprove", "void", "export"]),
  permissionsFor("production.progress", ["read"]),
  permissionsFor("production.completion", ["read"]),
  permissionsFor("production.payment", ["read"]),
  permissionsFor("inspection.order", ["read"]),
  allFor("inventory.stock"),
  allFor("inventory.transaction"),
  permissionsFor("inventory.alert", ["read"]),
  permissionsFor("inventory.adjustment", [
    "read",
    "approve",
    "reject",
    "unapprove",
    "void",
    "export",
  ]),
  permissionsFor("inventory.stock-count", ["read", "approve", "reject", "void", "export"]),
  permissionsFor("inventory.damage", ["read", "approve", "reject", "export"]),
  permissionsFor("inbound.order", ["read", "approve", "reject", "unapprove", "reverse", "export"]),
  permissionsFor("outbound.order", ["read", "approve", "reject", "unapprove", "reverse", "export"]),
  permissionsFor("outbound.sales-return", ["read", "approve", "reject", "export"]),
  permissionsFor("transfer.order", ["read", "approve", "reject", "unapprove", "export"]),
  permissionsFor("cross-border.shipment", [
    "read",
    "approve",
    "reject",
    "unapprove",
    "void",
    "export",
  ]),
  allFor("cross-border.overseas-inventory"),
  allFor("cross-border.import-result"),
  allFor("cross-border.source-trace"),
  permissionsFor("import.task", ["read"]),
  permissionsFor("import.template", ["read"]),
  allFor("import.history"),
  permissionsFor("attachment.file", ["read", "download"]),
  allFor("audit.log"),
  allFor("field.amount"),
  allFor("field.cost"),
  allFor("field.personal-data"),
  allFor("field.supplier-sensitive"),
  allFor("field.manufacturer-sensitive"),
  allFor("field.attachment-sensitive"),
  allFor("field.import-raw-data"),
  allFor("field.audit-sensitive"),
);

export const ROLE_PERMISSION_MAP: Readonly<Record<RoleCode, readonly PermissionCode[]>> =
  Object.freeze({
    administrator: PERMISSION_CODES,
    purchaser: PURCHASER_PERMISSIONS,
    warehouse_staff: WAREHOUSE_PERMISSIONS,
    sales_staff: SALES_PERMISSIONS,
    company_principal: PRINCIPAL_PERMISSIONS,
  });

const permissionCodeSet = new Set<string>(PERMISSION_CODES);

export function isPermissionCode(value: string): value is PermissionCode {
  return permissionCodeSet.has(value);
}
